import os
import random
import shutil
import pandas as pd
from ultralytics import YOLO

def prepare_and_train():
    # 1. Configuration
    DEBLUR_DIR = "deblurred_dataset"
    LABELS_DIR = "labels"
    DATASET_DIR = "yolo_dataset"
    PROJECT_NAME = "task4_training"
    RUN_NAME = "deblur_detector"

    TRAIN_RATIO = 0.7
    VAL_RATIO = 0.2

    # 2. Cleanup and Folder Creation
    if os.path.exists(DATASET_DIR):
        shutil.rmtree(DATASET_DIR)

    for split in ["train", "val", "test"]:
        os.makedirs(os.path.join(DATASET_DIR, "images", split), exist_ok=True)
        os.makedirs(os.path.join(DATASET_DIR, "labels", split), exist_ok=True)

    # 3. Load Images
    valid_exts = ('.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG')
    images = [f for f in os.listdir(DEBLUR_DIR) if f.lower().endswith(valid_exts)]

    if not images:
        print(f"Error: No images found in {DEBLUR_DIR}")
        return

    random.shuffle(images)

    # 4. Split Logic
    train_split = int(len(images) * TRAIN_RATIO)
    val_split = int(len(images) * (TRAIN_RATIO + VAL_RATIO))

    splits = {
        "train": images[:train_split],
        "val": images[train_split:val_split],
        "test": images[val_split:]
    }

    # 5. File Distribution
    print(f"Moving {len(images)} files...")
    count = 0
    for split, files in splits.items():
        for img_name in files:
            base_name = img_name.replace("deblurred_", "")
            label_name = os.path.splitext(base_name)[0] + ".txt"
            
            src_img = os.path.join(DEBLUR_DIR, img_name)
            src_lbl = os.path.join(LABELS_DIR, label_name)

            if os.path.exists(src_lbl):
                shutil.copy(src_img, os.path.join(DATASET_DIR, "images", split, img_name))
                shutil.copy(src_lbl, os.path.join(DATASET_DIR, "labels", split, label_name))
                count += 1

    print(f"Prepared {count} image/label pairs.")

    # 6. Training with Logging
    if count > 0:
        model = YOLO("yolov8n.pt")
        
        # Results are automatically stored in project/name/
        results = model.train(
            data="dataset.yaml",
            epochs=30,
            imgsz=640,
            batch=16,
            workers=0,
            project=PROJECT_NAME,
            name=RUN_NAME
        )
        
        # 7. Post-Training Analysis
        # Path to the results CSV generated by YOLO
        results_csv = os.path.join(PROJECT_NAME, RUN_NAME, "results.csv")
        
        if os.path.exists(results_csv):
            print("\n--- Training Analysis ---")
            df = pd.read_csv(results_csv)
            
            # Clean column names (YOLOv8 CSVs sometimes have leading/trailing spaces)
            df.columns = df.columns.str.strip()
            
            # Extract final metrics for the report [cite: 58]
            final_epoch = df.iloc[-1]
            print(f"Final mAP50: {final_epoch['metrics/mAP50(B)']:.4f}")
            print(f"Final mAP50-95: {final_epoch['metrics/mAP50-95(B)']:.4f}")
            print(f"Final Precision: {final_epoch['metrics/precision(B)']:.4f}")
            print(f"Final Recall: {final_epoch['metrics/recall(B)']:.4f}")
            
            # Save a summary for your presentation [cite: 12]
            summary_path = os.path.join(PROJECT_NAME, RUN_NAME, "training_summary.txt")
            with open(summary_path, "w") as f:
                f.write("Training Summary\n")
                f.write(f"Total Images: {len(images)}\n")
                f.write(f"Training Split: {len(splits['train'])}\n")
                f.write(f"Final mAP50: {final_epoch['metrics/mAP50(B)']}\n")
        
        print(f"\nAll logs and analysis saved to {os.path.join(PROJECT_NAME, RUN_NAME)}")

if __name__ == '__main__':
    prepare_and_train()